#!/bin/bash

# Change to the parent directory of where the script is located
cd "$(dirname "$0")/.."

cargo build --package prototype --target wasm32-unknown-unknown
cargo build --package othismo

rm -rf ./playground/^*.simg
mkdir -p ./playground
cp ./target/debug/othismo ./playground
cp ./target/wasm32-unknown-unknown/debug/prototype.wasm ./playground