[package]
name = "prototype"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-executor = { version = "1.13.2", features = ["static"] }
async-task = "4.7.1"


[dependencies.futures-util]
version = "0.3.4"
default-features = false
features = ["alloc"]
