[package]
name = "prototype"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]


[dependencies.futures-util]
version = "0.3.4"
default-features = false
features = ["alloc"]